export enum NotificationType {
  // User Management
  USER_CREATED = 'USER_CREATED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  
  // Events from .NET Core
  EVENT_CREATED = 'EVENT_CREATED',
  EVENT_APPROVED = 'EVENT_APPROVED',
  EVENT_REJECTED = 'EVENT_REJECTED',
  EVENT_PARTICIPATION_REQUESTED = 'EVENT_PARTICIPATION_REQUESTED',
  EVENT_PARTICIPATION_APPROVED = 'EVENT_PARTICIPATION_APPROVED',
  EVENT_PARTICIPATION_REJECTED = 'EVENT_PARTICIPATION_REJECTED',
  EVENT_COMMENT_ADDED = 'EVENT_COMMENT_ADDED',
  EVENT_COMMENT_REACTION = 'EVENT_COMMENT_REACTION',
  
  // Jobs from .NET Core
  JOB_APPLICATION_RECEIVED = 'JOB_APPLICATION_RECEIVED',
  JOB_INTERVIEW_SCHEDULED = 'JOB_INTERVIEW_SCHEDULED',
  JOB_APPLICATION_STATUS_CHANGED = 'JOB_APPLICATION_STATUS_CHANGED',
  JOB_RECOMMENDATION_RECEIVED = 'JOB_RECOMMENDATION_RECEIVED',
  
  // Social Network
  POST_CREATED = 'POST_CREATED',
  POST_LIKED = 'POST_LIKED',
  POST_COMMENTED = 'POST_COMMENTED',
  POST_SHARED = 'POST_SHARED',
  POST_MENTIONED = 'POST_MENTIONED',
  USER_FOLLOWED = 'USER_FOLLOWED',
  
  // Chat
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  CONVERSATION_CREATED = 'CONVERSATION_CREATED',
  GROUP_MESSAGE_RECEIVED = 'GROUP_MESSAGE_RECEIVED',
  
  // Admin
  CONTENT_FLAGGED = 'CONTENT_FLAGGED',
  USER_REPORTED = 'USER_REPORTED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  
  // General
  SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
  WELCOME = 'WELCOME',
}